local function make_repo(branch)
  local repo = vim.fn.tempname()
  vim.fn.mkdir(repo, "p")
  vim.system({ "git", "-C", repo, "init", "-q", "-b", branch or "main" }):wait()
  vim.system({ "git", "-C", repo, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "--allow-empty", "-m", "i" }):wait()
  return repo
end

describe("pier.session new", function()
  local config = require("pier.config")
  local session_mod = require("pier.session")
  local ui = require("pier.ui")
  local saved

  before_each(function()
    saved = config.options.cache_dir
    config.options.cache_dir = vim.fn.tempname()
  end)

  after_each(function()
    config.options.cache_dir = saved
  end)

  it("refuses while busy and keeps pending context", function()
    local repo = make_repo()
    local old = session_mod.for_path(repo)
    old:add_context("ctx")
    old.busy = true
    local new, err = session_mod.new(old)
    assert.is_nil(new)
    assert.is_truthy(err:find("busy"))
    assert.are.same({ "ctx" }, old:pending_context_blocks())
    assert.is_falsy(old.superseded)
    old.busy = false
  end)

  it("keeps the old session and context when the override cannot be written", function()
    local repo = make_repo()
    local old = session_mod.for_path(repo)
    old:add_context("ctx")
    vim.fn.mkdir(config.options.cache_dir, "p")
    local f = io.open(config.options.cache_dir .. "/session-overrides.json", "w")
    f:write("{not json")
    f:close()
    local new, err = session_mod.new(old)
    assert.is_nil(new)
    assert.is_truthy(err:find("corrupt"))
    assert.are.same({ "ctx" }, old:pending_context_blocks())
    assert.is_falsy(old.superseded)
  end)

  it("supersedes the old session and routes current() from the old buffer to the new one", function()
    local repo = make_repo()
    local old = session_mod.for_path(repo)
    old:add_context("ctx")
    local old_buf = ui.buffer(old)
    vim.api.nvim_set_current_buf(old_buf)
    local new = session_mod.new(old)
    assert.is_truthy(new)
    assert.are_not.equal(old.id, new.id)
    assert.is_true(old.superseded)
    assert.are.same({}, old:pending_context_blocks())
    assert.are.equal(new, session_mod.current())
    assert.is_false(old:ask("hello"))
    assert.is_nil(old.rpc)
    assert.are.equal(ui.buffer(new), vim.api.nvim_get_current_buf())
  end)

  it("replaces the scope of the session buffer even after the checkout changes branch", function()
    local repo = make_repo("main")
    local old = session_mod.for_path(repo)
    vim.system({ "git", "-C", repo, "checkout", "-q", "-b", "other" }):wait()
    local other = session_mod.for_path(repo)
    assert.are_not.equal(old.id, other.id)
    local new = session_mod.new(old)
    assert.are.equal("main", new.info.branch)
    assert.is_true(old.superseded)
    assert.is_falsy(other.superseded)
    assert.are.equal(other, session_mod.for_path(repo))
  end)

  it("revives a superseded session when its override is deleted", function()
    local repo = make_repo()
    local old = session_mod.for_path(repo)
    local new = session_mod.new(old)
    assert.is_truthy(new)
    os.remove(config.options.cache_dir .. "/session-overrides.json")
    local again = session_mod.for_path(repo)
    assert.are.equal(old, again)
    assert.is_falsy(again.superseded)
  end)
end)
